// Baza slow do gry w zgadywanie (dla dzieci 6-7 lat).
// Kazde slowo ma podpowiedz opisowa zrozumiala dla dziecka.
// Slowa 3-7 liter, proste i znane.

class SlowoZagadka {
  final String slowo; // poprawna forma z polskimi znakami
  final String podpowiedz;

  const SlowoZagadka(this.slowo, this.podpowiedz);
}

// Lista slow. Kolejnosc nie ma znaczenia - gra losuje.
const List<SlowoZagadka> bazaSlow = [
  // --- czesci ciala ---
  SlowoZagadka('łokieć', 'Zginająca się część ręki między dłonią a ramieniem.'),
  SlowoZagadka('kolano', 'Zgina się w środku nogi, gdy kucasz.'),
  SlowoZagadka('nos', 'Masz go na środku twarzy i nim wąchasz.'),
  SlowoZagadka('ucho', 'Jest po bokach głowy i nim słyszysz.'),
  SlowoZagadka('oko', 'Masz dwoje i nimi patrzysz.'),
  SlowoZagadka('ręka', 'Masz dwie, a na końcu każdej jest dłoń z palcami.'),
  SlowoZagadka('noga', 'Masz dwie i chodzisz na nich.'),
  SlowoZagadka('palec', 'Masz ich pięć na każdej dłoni.'),
  SlowoZagadka('włosy', 'Rosną na głowie, można je czesać.'),
  SlowoZagadka('zęby', 'Białe, w buzi, gryziesz nimi jedzenie.'),
  SlowoZagadka('język', 'Różowy, w buzi, czujesz nim smak.'),
  SlowoZagadka('brzuch', 'Tu trafia jedzenie, gdy je zjesz.'),
  SlowoZagadka('serce', 'Bije w piersi cały czas, stuk-stuk.'),
  SlowoZagadka('włos', 'Jeden z wielu na twojej głowie.'),
  SlowoZagadka('broda', 'Dolna część twarzy, pod ustami.'),

  // --- zwierzeta ---
  SlowoZagadka('kot', 'Miauczy i lubi mleko, domowy pupil.'),
  SlowoZagadka('pies', 'Szczeka i macha ogonem, najlepszy przyjaciel człowieka.'),
  SlowoZagadka('krowa', 'Robi "muu" i daje mleko.'),
  SlowoZagadka('koń', 'Duże zwierzę, można na nim jeździć, robi "ihaha".'),
  SlowoZagadka('kura', 'Znosi jajka i robi "ko-ko".'),
  SlowoZagadka('kaczka', 'Pływa po stawie i robi "kwa-kwa".'),
  SlowoZagadka('świnia', 'Różowa, mieszka w chlewiku, robi "chrum".'),
  SlowoZagadka('owca', 'Ma białą wełnę i robi "bee".'),
  SlowoZagadka('koza', 'Ma rogi i lubi skakać, daje mleko.'),
  SlowoZagadka('ryba', 'Pływa w wodzie i oddycha skrzelami.'),
  SlowoZagadka('żaba', 'Zielona, skacze i robi "kum-kum".'),
  SlowoZagadka('mysz', 'Mała, szara, boi się jej kot, lubi ser.'),
  SlowoZagadka('lis', 'Rudy, sprytny, ma puszysty ogon.'),
  SlowoZagadka('wilk', 'Dziki krewny psa, wyje do księżyca.'),
  SlowoZagadka('niedźwiedź', 'Duży, brązowy, lubi miód i śpi zimą.'),
  SlowoZagadka('zając', 'Ma długie uszy i szybko skacze.'),
  SlowoZagadka('jeż', 'Mały, cały w kolcach, zwija się w kulkę.'),
  SlowoZagadka('sowa', 'Ptak, który nie śpi w nocy, robi "hu-hu".'),
  SlowoZagadka('bocian', 'Duży ptak, przynosi wiosnę, je żaby.'),
  SlowoZagadka('paw', 'Ptak z pięknym, kolorowym ogonem.'),
  SlowoZagadka('pszczoła', 'Robi miód i może użądlić.'),
  SlowoZagadka('motyl', 'Ma kolorowe skrzydła i lata nad kwiatami.'),
  SlowoZagadka('mrówka', 'Malutka, silna, mieszka w mrowisku.'),
  SlowoZagadka('słoń', 'Bardzo duży, szary, ma trąbę.'),
  SlowoZagadka('żyrafa', 'Ma bardzo długą szyję.'),
  SlowoZagadka('lew', 'Król zwierząt, ma grzywę i głośno ryczy.'),
  SlowoZagadka('tygrys', 'Duży kot w paski, mieszka w dżungli.'),
  SlowoZagadka('małpa', 'Lubi banany i skacze po drzewach.'),
  SlowoZagadka('zebra', 'Koń w czarno-białe paski.'),
  SlowoZagadka('foka', 'Pływa w zimnym morzu, ma płetwy.'),
  SlowoZagadka('delfin', 'Mądre zwierzę morskie, lubi skakać z wody.'),
  SlowoZagadka('rekin', 'Duża ryba z ostrymi zębami.'),
  SlowoZagadka('ślimak', 'Wolno się porusza i nosi domek na plecach.'),
  SlowoZagadka('pająk', 'Ma osiem nóg i tka pajęczynę.'),
  SlowoZagadka('biedronka', 'Czerwona z czarnymi kropkami.'),

  // --- jedzenie ---
  SlowoZagadka('chleb', 'Kroisz go i robisz kanapki.'),
  SlowoZagadka('masło', 'Żółte, smarujesz nim chleb.'),
  SlowoZagadka('ser', 'Robi się z mleka, żółty z dziurami.'),
  SlowoZagadka('mleko', 'Białe, pijesz je, daje krowa.'),
  SlowoZagadka('jajko', 'Znosi je kura, robisz z niego jajecznicę.'),
  SlowoZagadka('jabłko', 'Czerwone lub zielone, rośnie na drzewie.'),
  SlowoZagadka('gruszka', 'Słodki owoc, kształtem jak żarówka.'),
  SlowoZagadka('banan', 'Żółty, zakrzywiony owoc, lubią go małpy.'),
  SlowoZagadka('śliwka', 'Fioletowy owoc z pestką w środku.'),
  SlowoZagadka('wiśnia', 'Mały, czerwony owoc na ogonku.'),
  SlowoZagadka('malina', 'Czerwona, słodka, rośnie na krzaku.'),
  SlowoZagadka('cytryna', 'Żółta i bardzo kwaśna.'),
  SlowoZagadka('marchew', 'Pomarańczowa, chrupiąca, lubią ją zające.'),
  SlowoZagadka('ziemniak', 'Rośnie pod ziemią, robisz z niego frytki.'),
  SlowoZagadka('pomidor', 'Czerwony, okrągły, dobry do zupy.'),
  SlowoZagadka('ogórek', 'Zielony i długi, dobry do kanapki.'),
  SlowoZagadka('cebula', 'Gdy ją kroisz, płaczą oczy.'),
  SlowoZagadka('grzyb', 'Rośnie w lesie, ma nóżkę i kapelusz.'),
  SlowoZagadka('zupa', 'Ciepłe, jesz łyżką z talerza.'),
  SlowoZagadka('cukier', 'Biały, słodki, dodajesz do herbaty.'),
  SlowoZagadka('miód', 'Słodki, złoty, robią go pszczoły.'),
  SlowoZagadka('lody', 'Zimne i słodkie, jesz latem.'),
  SlowoZagadka('ciasto', 'Słodkie, pieczesz je na urodziny.'),
  SlowoZagadka('herbata', 'Ciepły napój, pijesz z kubka.'),
  SlowoZagadka('woda', 'Przezroczysta, pijesz ją, gdy chce ci się pić.'),

  // --- dom i przedmioty ---
  SlowoZagadka('stół', 'Ma cztery nogi, jesz przy nim obiad.'),
  SlowoZagadka('krzesło', 'Siadasz na nim.'),
  SlowoZagadka('łóżko', 'Śpisz na nim w nocy.'),
  SlowoZagadka('szafa', 'Trzymasz w niej ubrania.'),
  SlowoZagadka('okno', 'Patrzysz przez nie na zewnątrz.'),
  SlowoZagadka('drzwi', 'Otwierasz je, żeby wejść do pokoju.'),
  SlowoZagadka('lampa', 'Świeci i oświetla pokój.'),
  SlowoZagadka('zegar', 'Pokazuje, która jest godzina.'),
  SlowoZagadka('talerz', 'Okrągły, kładziesz na nim jedzenie.'),
  SlowoZagadka('kubek', 'Pijesz z niego, ma uszko.'),
  SlowoZagadka('łyżka', 'Jesz nią zupę.'),
  SlowoZagadka('widelec', 'Ma zęby, nabijasz na niego jedzenie.'),
  SlowoZagadka('nóż', 'Kroisz nim jedzenie, jest ostry.'),
  SlowoZagadka('garnek', 'Gotujesz w nim zupę na kuchence.'),
  SlowoZagadka('mydło', 'Myjesz nim ręce, robi pianę.'),
  SlowoZagadka('ręcznik', 'Wycierasz się nim po kąpieli.'),
  SlowoZagadka('szczotka', 'Czeszesz nią włosy.'),
  SlowoZagadka('klucz', 'Otwierasz nim zamek w drzwiach.'),
  SlowoZagadka('książka', 'Ma strony, czytasz ją.'),
  SlowoZagadka('ołówek', 'Rysujesz nim, można gumką zetrzeć.'),
  SlowoZagadka('kredka', 'Kolorowa, rysujesz nią obrazki.'),
  SlowoZagadka('nożyczki', 'Tniesz nimi papier.'),
  SlowoZagadka('piłka', 'Okrągła, kopiesz ją lub rzucasz.'),
  SlowoZagadka('lalka', 'Zabawka, wygląda jak mała osoba.'),
  SlowoZagadka('miś', 'Pluszowa zabawka, przytulasz go do snu.'),

  // --- przyroda i pogoda ---
  SlowoZagadka('słońce', 'Świeci na niebie w dzień, jest ciepłe.'),
  SlowoZagadka('księżyc', 'Świeci na niebie w nocy.'),
  SlowoZagadka('gwiazda', 'Malutkie światełko na nocnym niebie.'),
  SlowoZagadka('chmura', 'Biała na niebie, z niej pada deszcz.'),
  SlowoZagadka('deszcz', 'Kapie z nieba, bierzesz parasol.'),
  SlowoZagadka('śnieg', 'Biały, pada zimą, lepisz z niego bałwana.'),
  SlowoZagadka('tęcza', 'Kolorowy łuk na niebie po deszczu.'),
  SlowoZagadka('wiatr', 'Nie widać go, ale czujesz, jak wieje.'),
  SlowoZagadka('drzewo', 'Ma pień, gałęzie i liście, rośnie w lesie.'),
  SlowoZagadka('kwiat', 'Kolorowy, ładnie pachnie, rośnie na łące.'),
  SlowoZagadka('trawa', 'Zielona, rośnie na trawniku.'),
  SlowoZagadka('liść', 'Zielony, rośnie na drzewie, spada jesienią.'),
  SlowoZagadka('las', 'Rośnie w nim dużo drzew, mieszkają tam zwierzęta.'),
  SlowoZagadka('rzeka', 'Płynie w niej woda, można w niej pływać.'),
  SlowoZagadka('morze', 'Bardzo dużo słonej wody, jeździsz nad nie latem.'),
  SlowoZagadka('góra', 'Bardzo wysoka, wspinasz się na nią.'),
  SlowoZagadka('kamień', 'Twardy, leży na ziemi.'),
  SlowoZagadka('piasek', 'Jest go dużo na plaży, sypki.'),
  SlowoZagadka('ogień', 'Gorący, świeci i parzy, pali się.'),
  SlowoZagadka('lód', 'Zamarznięta woda, zimny i śliski.'),

  // --- pojazdy ---
  SlowoZagadka('auto', 'Ma cztery koła, jeździsz nim po drodze.'),
  SlowoZagadka('rower', 'Ma dwa koła, pedałujesz nogami.'),
  SlowoZagadka('pociąg', 'Długi, jedzie po szynach, robi "ciuch-ciuch".'),
  SlowoZagadka('samolot', 'Lata w powietrzu, ma skrzydła.'),
  SlowoZagadka('statek', 'Duży, pływa po morzu.'),
  SlowoZagadka('łódka', 'Mała, pływa po wodzie, ma wiosła.'),
  SlowoZagadka('autobus', 'Duży, wozi wielu ludzi po mieście.'),
  SlowoZagadka('traktor', 'Jeździ po polu, pomaga rolnikowi.'),
  SlowoZagadka('rakieta', 'Leci w kosmos, do gwiazd.'),
  SlowoZagadka('taksówka', 'Auto, którym jedziesz i płacisz za jazdę.'),

  // --- ludzie i zawody ---
  SlowoZagadka('mama', 'Twoja rodzicielka, kobieta.'),
  SlowoZagadka('tata', 'Twój rodzic, mężczyzna.'),
  SlowoZagadka('babcia', 'Mama twojej mamy lub taty.'),
  SlowoZagadka('dziadek', 'Tata twojej mamy lub taty.'),
  SlowoZagadka('siostra', 'Dziewczynka, córka twoich rodziców.'),
  SlowoZagadka('brat', 'Chłopiec, syn twoich rodziców.'),
  SlowoZagadka('lekarz', 'Leczy chorych ludzi.'),
  SlowoZagadka('strażak', 'Gasi pożary, jeździ czerwonym wozem.'),
  SlowoZagadka('policjant', 'Pilnuje porządku, łapie złodziei.'),
  SlowoZagadka('kucharz', 'Gotuje jedzenie w restauracji.'),
  SlowoZagadka('nauczyciel', 'Uczy dzieci w szkole.'),
  SlowoZagadka('rolnik', 'Uprawia pole i hoduje zwierzęta.'),
  SlowoZagadka('listonosz', 'Przynosi listy i paczki.'),
  SlowoZagadka('król', 'Rządzi królestwem, nosi koronę.'),

  // --- ubrania ---
  SlowoZagadka('buty', 'Zakładasz je na stopy.'),
  SlowoZagadka('czapka', 'Zakładasz na głowę, gdy jest zimno.'),
  SlowoZagadka('szalik', 'Owijasz nim szyję zimą.'),
  SlowoZagadka('kurtka', 'Zakładasz ją, gdy na dworze jest chłodno.'),
  SlowoZagadka('spodnie', 'Zakładasz je na nogi.'),
  SlowoZagadka('sukienka', 'Nosi ją dziewczynka, jednoczęściowa.'),
  SlowoZagadka('skarpetki', 'Zakładasz je na stopy pod buty.'),
  SlowoZagadka('rękawiczki', 'Zakładasz na dłonie, gdy jest zimno.'),

  // --- inne proste ---
  SlowoZagadka('dom', 'Mieszkasz w nim z rodziną.'),
  SlowoZagadka('szkoła', 'Chodzisz tam się uczyć.'),
  SlowoZagadka('sklep', 'Kupujesz w nim jedzenie i inne rzeczy.'),
  SlowoZagadka('park', 'Zielone miejsce, bawisz się tam na huśtawce.'),
  SlowoZagadka('most', 'Przechodzisz po nim nad rzeką.'),
  SlowoZagadka('droga', 'Jeżdżą po niej samochody.'),
  SlowoZagadka('płot', 'Otacza ogród, żeby nikt nie wszedł.'),
  SlowoZagadka('dach', 'Jest na górze domu, chroni przed deszczem.'),
  SlowoZagadka('schody', 'Wchodzisz po nich na górę.'),
  SlowoZagadka('winda', 'Wozi cię w górę i w dół w wysokim domu.'),
  SlowoZagadka('zabawka', 'Bawisz się nią, gdy masz wolny czas.'),
  SlowoZagadka('bajka', 'Opowiadanie dla dzieci, często ze zwierzętami.'),
  SlowoZagadka('piosenka', 'Śpiewasz ją, ma melodię i słowa.'),
  SlowoZagadka('urodziny', 'Twoje święto raz w roku, jest tort.'),
  SlowoZagadka('prezent', 'Dostajesz go zapakowany na urodziny.'),
  SlowoZagadka('balon', 'Kolorowy, nadmuchujesz go, lata w górę.'),
  SlowoZagadka('świeca', 'Pali się małym płomykiem, wtykasz w tort.'),
  SlowoZagadka('parasol', 'Chroni cię przed deszczem.'),
  SlowoZagadka('zdjęcie', 'Robisz je aparatem, żeby coś zapamiętać.'),
  SlowoZagadka('mapa', 'Pokazuje drogi i miejsca, żeby się nie zgubić.'),
];
