name: gry_podrozne
description: Zestaw prostych gier podroznych na jeden telefon (2-3 osoby).
publish_to: 'none'
version: 1.5.0+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Numer wersji aplikacji (pokazywany w menu)
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
